name: testes

on:
  workflow_dispatch:

jobs:
  rapido:
    name: 'estagios 1 e 2: build, unidade e API'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: alo
        run: echo "a esteira executou"