name: testes

on:
  workflow_dispatch:

jobs:
  rapido:
    name: 'testando esteira'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout do SUT (commit em analise)
        uses: actions/checkout@v5
        with:
          path: sut-didatico

      - name: checkout da TAS (onde vivem os testes)
        uses: actions/checkout@v5
        with:
          repository: HayCESAR/tas-cidade-conectada
          ref: main
          path: tas

      - name: onde eu estou
        run: |
          echo "workspace: $GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE"
